name: Selenium Wire Test

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # Runs daily at 02:00 UTC (05:00 AM Qatar time)

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libssl-dev
        python -m pip install --upgrade pip
        pip install selenium==4.0.0 selenium-wire==4.0.0 mitmproxy==7.0.0 pandas

    - name: Run Selenium Wire script
      run: |
        xvfb-run -a python -c "
        import os
        import pandas as pd
        from seleniumwire import webdriver
        from selenium.webdriver.common.by import By
        from selenium.webdriver.common.keys import Keys

        # Setup Selenium WebDriver
        options = webdriver.ChromeOptions()
        driver = webdriver.Chrome(seleniumwire_options={}, options=options)

        # Perform login and get the token
        driver.get('https://www.tilastopaja.info/beta/users/login.php')
        driver.find_element(By.NAME, 'username').send_keys('aspiretf')
        driver.find_element(By.NAME, 'password').send_keys('Qcus4rGA9RaK', Keys.RETURN)
        driver.implicitly_wait(10)
        driver.get('https://www.tilastopaja.info/api/competitions/latest?&major=true&country=world')

        auth_token = None
        for request in driver.requests:
            if request.response and 'authorization' in request.headers:
                auth_token = request.headers['authorization']
                print(f'Authorization token found: {auth_token}')
                break
        driver.quit()

        # Save the token to a CSV
        if auth_token:
            df = pd.DataFrame({'Authorization Token': [auth_token]})
            df.to_csv('./auth_token.csv', index=False)
            print('Authorization token saved to auth_token.csv.')
        else:
            print('Authorization token not found.')
        "

    - name: Push updated auth_token.csv
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add ./auth_token.csv
        git commit -m "Update auth_token.csv with latest token" || echo "No changes to commit."
        git push origin HEAD
