name: Selenium Wire Test

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libssl-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium==4.0.0 selenium-wire==4.0.0 mitmproxy==7.0.0 requests packaging blinker pandas==2.0.3 tqdm==4.65.0 sqlalchemy==2.0.19 python-dotenv==1.0.0

      - name: Run the update python script
        env:
          DISPLAY: ":99.0"
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          Xvfb :99 -ac &
          sleep 5 # Give Xvfb some time to start
          python Daily_update_Tila.py
