name: Tila Daily update

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libssl-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy==1.21.0 pandas==1.3.0
          pip install selenium==4.0.0 selenium-wire==4.0.0 mitmproxy==7.0.0 requests packaging blinker tqdm==4.65.0 sqlalchemy==1.4.22 python-dotenv==1.0.0 pymysql==1.0.2 pyarrow

      - name: Run the update python script
        env:
          DISPLAY: ":99.0"
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          Xvfb :99 -ac &
          sleep 5 # Give Xvfb some time to start
          python One_get_Tila_info.py

      - name: Commit results
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add results_df.parquet results_df.csv
          git commit -m 'Add results_df Parquet and CSV files'
          git push

      - name: Set up environment variables
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: echo "DB_PASSWORD is set"

      - name: Run database operations
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          python two_database_update.py
