name: Tilastopija daily update of MySQL

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the update python script
        env:
          DISPLAY: ":99.0"
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          Xvfb :99 -ac &
          sleep 3 # Give Xvfb some time to start
          python Daily_update_Tila.py
