name: Tilastopija daily update of MySQL

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium==4.18.1 seleniumwire==5.1.o requests==2.31.0 pandas==2.2.1 tqdm==4.66.2 sqlalchemy==2.0.29 python-dotenv==1.0.1 pyarrow==15.0.0


      - name: Run the update python script
        env:
          DISPLAY: ":99.0"
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          Xvfb :99 -ac &
          sleep 3 # Give Xvfb some time to start
          python Daily_update_Tila.py
